version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 'sudo npm install -g npm@6.4.1'
      - run: 'npm install'
      - run: 'npm run build'
